### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by WaluigiBSOD** [WaluigiBSOD/asge-creditscheat-tool#1]
# Code

- [x] Add better file I/O error handling
- [x] Add dynamic memory allocation error handling
- [x] Check for grammatical errors in the comments of the source code

# Documentation

- [x] Documentation is mostly broken when browsing it remotely due to [a missing Jekyll override introduced at the end of 2009](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/), as HTML pages generated by Doxygen that begin with an underscore yield 404 errors with GitHub Pages
- [x] Check for grammatical errors in the `main.dox` source file
- [x] Add a `404.html` 404 error handler in the root of the website that redirects to the main page

# Files

- [x] CSV files do their job, but the program was designed to comply with Microsoft Excel 2021'demands (specifically with the European regional setting of using a semicolon as a list separator instead of a comma), not by outputting proper CSV files GitHub can handle
